### ISSUE TITLE
Disabling hide-mode-line-mode doesn't bring the mode-line back

### ISSUE THREAD

**Issue by mrcnski** [hlissner/emacs-hide-mode-line#2] opened 2018-03-07 08:43 UTC
I run `hide-mode-line-mode` once and it works beautifully. Thanks for that.

I run it again in the same buffer. Omg, there's no mode-line! I can make out the following message in the final moments before I pass into a faint:

`Hide-Mode-Line mode disabled in current buffer`

But no mode-line!!

**Comment by hlissner** [comment] 2018-03-07 22:41
> Words breach the unconscious void. You imagine a one-eyed, horned meatball speaking to you. He fails a perception check; he doesn't notice you're a bear.

I'm unable to reproduce the issue. What version of Emacs are you running, and what major mode(s) do you get this behavior in (or can you reproduce it consistently across all buffers)?

**Comment by mrcnski** [comment] 2018-03-08 06:11
Have you tried calling `hide-mode-line-mode` with a keybinding? When I run `M-x hide-mode-line-mode` it works as expected, but using my keybinding `s-m`, the mode-line doesn't appear. To be more clear, the mode-line comes back but it is invisible, and I have to do something like switch buffers in order for it to be drawn. I observed this behavior in every mode I tried.

Let's hope you can reproduce it now. :menacing glare:

`M-x emacs-version`:
`GNU Emacs 25.2.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911)) of 2017-04-21`

**Comment by hlissner** [comment] 2018-03-09 10:31
I am one unflatteringly flummuxed floating meatball. I can reproduce this on Emacs 25, 26 and 27.

The clumsy fix for this would be:

```elisp
(defun hide-mode-line-toggle ()
  (interactive)
  (hide-mode-line-mode (if hide-mode-line-mode -1 +1))
  (unless hide-mode-line-mode
    (redraw-display)))
```

Bind that key of yours to `hide-mode-line-toggle` instead. That should stave off this weird bug while I prepare a ritual sacrifice (and pray for a better solution).

**Comment by mrcnski** [comment] 2018-03-09 10:44
Thanks, the code snippet works. My screen does flicker a bit, though -- `redraw-display` is probably overkill.

> I am one unflatteringly flummuxed floating meatball.

It's only natural that I should defeat you -- I am a professional demon hunter, after all.

**Comment by WorldsEndless** [comment] 2019-09-23 21:25
Thank you for the code-snippet. I used it without `redraw-display` and it works great. I now have a hotkey for `global-hide-mode-line-mode` and, when called with an arg, toggles window specific modeline (the rarer case for me).

**Comment by WorldsEndless** [comment] 2019-09-25 17:35
Correction: after restarting emacs, neither toggle works, even with the redraw-display. If I toggle once, the modeline(s) go away; but there seems to be no way to bring them back, regardless of what args I pass to their functions. 

Here is my code:
``` elisp
(defun tsa/hide-mode-line (arg)
  "Toggle modeline globally, or just in this window with arg"
  (interactive "p")
  (if (= arg 4)
      (progn
	(message "toggle buffer modeline from %s" hide-mode-line-mode)
	(hide-mode-line-mode (if hide-mode-line-mode -1 +1)))
    (progn
      (message "toggle global modeline from %s" global-hide-mode-line-mode)
      (global-hide-mode-line-mode))))
```

I see that toggling the buffer modeline is indeed telling me that it's value is alternating; however, the value of `global-hide-mode-line-mode` does not change (I've tried giving it args but to no avail).

**Comment by WorldsEndless** [comment] 2019-09-25 18:45
Correction: after restarting emacs, toggling per-buffer works until I attempt to toggle globally. Once I've done global-hide-modeline there is no recovering the modeline without restarting emacs. This is referenced in issue #4 .

**Comment by mpereira** [comment] 2019-12-19 12:51
I am seeing this as well. When `hide-mode-line-mode` is added to a hook, I am unable to disable it with `M-x hide-mode-line-mode` or by evaluating `(hide-mode-line-mode)` or `(hide-mode-line-mode -1)`.

The `hide-mode-line-toggle` function provided above also doesn't work.

macOS 10.14.4
Emacs 26.3
hide-mode-line 1.0.2 (20190922.115)

**Comment by hlissner** [comment] 2021-11-12 14:02
Sorry for the _super_ late response. cc81ba3 should finally fix this issue. Let me know if that isn't the case and I'll reopen it. Thanks for bringing it to my attention!

**Closed as completed** 2021-11-12 14:01 UTC
Labels: bug
