### ISSUE TITLE
Mode line is visible despite hide-mode-line-mode

### ISSUE THREAD

**Issue by indigoviolet** [hlissner/emacs-hide-mode-line#9] opened 2022-03-30 02:11 UTC
### What did you expect to happen?

mode-line should have been disabled.

### What actually happened?

I'm attempting to disable the mode-line in https://github.com/casouri/vundo

![image](https://user-images.githubusercontent.com/114010/160722953-043f96f5-e8ae-4088-83b9-07b8ea23490b.png)

There is some inconsistent state, first: the mode is on (since I have added it to `vundo--mode-hook`), but the modeline is visible.

Next, I run `hide-mode-line-mode` from M-x, and the mode is disabled, but the modeline disappears.

![image](https://user-images.githubusercontent.com/114010/160723000-d93a456e-61fe-4bf8-a926-7f9089a7656b.png)

Next, I run it again, and the mode is enabled, but the modeline is not:

![image](https://user-images.githubusercontent.com/114010/160723074-51239de4-2811-4f26-a5ab-9271853fb5b2.png)

### Describe your attempts to resolve the issue

I have this hook:

```elisp
(add-hook! 'vundo--mode-hook (visual-line-mode -1) (setq window-size-fixed t) #'hide-mode-line-mode)
```

~In case it is relevant~ I'm using the `+light` modeline  from doom-emacs `:ui` - this *only* happens with `+light` turned on, and does not happen with the "standard" doom-modeline

### Steps to reproduce
0. doom-emacs with `:ui (modeline +light)`

1.  `(package! vundo :recipe (:host github :repo "casouri/vundo"))`

2. `(add-hook! 'vundo--mode-hook #'hide-mode-line-hook)`

3. M-x `vundo` in a buffer with some undo history

### Package commit

doom-emacs with updated packages

### System Information

Ubuntu 21.04, doom-emacs, updated packages

**Comment by t-e-r-m** [comment] 2022-04-03 06:07
This is also the case for scratch buffers.

**Comment by hlissner** [comment] 2024-08-28 22:14
Sorry for the extraordinarily late response, but I cannot reproduce this. Do you still see this issue?

**Comment by hlissner** [comment] 2024-08-28 22:16
Oh, hold up. The problem is with your `add-hook!`.

```elisp
(add-hook! 'vundo--mode-hook (visual-line-mode -1) (setq window-size-fixed t) #'hide-mode-line-mode)
```

This isn't doing what you think it does. It expands to:

```elisp
(add-hook 'vundo--mode-hook
          (lambda (&rest _)
            (visual-line-mode -1)
            (setq window-size-fixed t)
            (function hide-mode-line-mode)))  ;; `hide-mode-line-mode` isn't getting called here
```

Use one of these instead:

```elisp
(add-hook! 'vundo--mode-hook (visual-line-mode -1) (setq window-size-fixed t))
(add-hook 'vundo--mode-hook #'hide-mode-line-mode)

;; OR

(add-hook! 'vundo--mode-hook (visual-line-mode -1) (setq window-size-fixed t) (hide-mode-line-mode +1))
```

I'll close this since it doesn't appear to be a bug with the package.

**Closed as not planned by hlissner** 2024-08-28 22:16 UTC
Labels: bug
